include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - lib/**/*.g.dart # json_serializable uses dynamic instead of Object
#    - lib/**/*.freezed.dart
    - lib/generated/intl/messages_en.dart
    - lib/generated/intl/messages_all.dart

linter:
  rules:
    # Additional rules from https://dart-lang.github.io/linter/lints/
    always_put_control_body_on_new_line: true
    await_only_futures: true
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    non_constant_identifier_names: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    sort_child_properties_last: true
    unnecessary_getters_setters: true
    # Excluded rules from https://github.com/flutter/packages/blob/master/packages/flutter_lints/lib/flutter.yaml
    eol_at_end_of_file: false
    lines_longer_than_80_chars: false
    use_key_in_widget_constructors: false
    avoid_print: false
