include: package:strict_flutter_lints/lints.yaml

dart_code_metrics:
  rules:
    - no-magic-number:
        exclude:
          - lib/presentation/**

analyzer:
  exclude:
    - lib/util/di/dependency_injection.config.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

