name: firebase_chat
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.2.0
  connectivity_plus: ^3.0.2
  dartx: ^1.1.0
  dio: ^4.0.6
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_performance: ^0.9.0+7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.16
  flutter_svg: ^1.1.6
  flutter_utils:
    git: https://github.com/erfactor/flutter_utils.git
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  hooks_riverpod: ^2.1.1
  json_annotation: ^4.7.0
  logger: ^1.1.0
  retrofit: ^3.3.1
  rxdart: ^0.27.7
  shimmer: ^2.0.0
  stack_trace: ^1.10.0

dev_dependencies:
  build_runner: ^2.3.2
  dart_code_metrics: ^5.2.1
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  strict_flutter_lints:
    git: https://github.com/erfactor/strict_flutter_lints.git

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/adaptive_app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/adaptive_app_icon.png"

flutter_native_splash:
  background_image: "assets/images/splash.png"
