name: firebase_chat
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.2
  dartx: ^1.1.0
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.3
  recase: ^4.0.0
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  google_sign_in: ^5.3.0
  firebase_crashlytics: ^2.7.2
  firebase_performance: ^0.8.0+11
  firebase_analytics: ^9.1.7
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  injectable: ^1.5.3
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  get_it: ^7.2.0
  connectivity_plus: ^2.3.0
  oktoast: ^3.1.5
  flutter_native_splash: ^2.1.6
  firebase_storage: ^10.2.15

dev_dependencies:
  flutter_lints: ^1.0.4
  build_runner: ^2.1.10
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.1
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#2cb88b"
  adaptive_icon_foreground: "assets/images/adaptive_app_icon.png"

flutter_native_splash:
  background_image: "assets/images/splash.png"
